### PR TITLE
v0.9.0.6

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by jjr840430** [comment]
@drystone Currently it has building issue due to `HAVE_LIBBSD` macro.
`getprogname` exists on macOS too, so it's enabled on macOS building.

Can you please check and fix? Thanks!

**Comment by jjr840430** [comment]
@drystone I removed HAVE_LIBBSD macro and added HAVE_GETPROGNAME.
Please review and check the last commit.

**Comment by drystone** [comment]
Hi @jjr840430, sorry if I broke the build.

The build is failing at `ucl_test.c`:
```
ucl_test.c: In function ‘ucl_obj_dump’:
ucl_test.c:184:4: warning: implicit declaration of function ‘strlcpy’ [-Wimplicit-function-declaration]
    strlcpy(cfg->key, obj->key, sizeof(cfg->key));
    ^~~~~~~
ucl_test.c: In function ‘main’:
ucl_test.c:256:38: warning: implicit declaration of function ‘getprogname’ [-Wimplicit-function-declaration]
   fprintf(stderr, "%s <HCL file>\n", getprogname());
                                      ^~~~~~~~~~~
ucl_test.c:256:21: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
   fprintf(stderr, "%s <HCL file>\n", getprogname());
                     ^
```
I've nothing against your `slrlcpy` and `strlcat` but they are already available on debian in libbsd :)

**Comment by jjr840430** [comment]
@drystone I will fix that issue on next pull request. Thanks for your comments.

**Pull request merged**
